### PR TITLE
Team page text overlap fix

### PR DESCRIPTION
**Pull request by matt-henriksen**
Fixes bug with both text-overlap on the media page as well as text getting cut off on the right side of the window as the window is resized.

### CODE REVIEW

**Comment by IanSaucy** [comment]
This looks like a good improvement. A few things I noticed.

I'm guessing as a result of the mobile cutoff change, the bug where the menu gets clipped and or looks like the below image is back. 
image

The buffer problem has been fixed for the team page. That being said, when it goes to single column the photos are not aligned with their respective text.

**Comment by matt-henriksen** [comment]
> This looks like a good improvement. A few things I noticed.
> 
> I'm guessing as a result of the mobile cutoff change, the bug where the menu gets clipped and or looks like the below image is back. image
> 
> The buffer problem has been fixed for the team page. That being said, when it goes to single column the photos are not aligned with their respective text.

Good catch... I'll work on getting the menu compatible with these changes as well as centering the photos on the team page!

**Comment by IanSaucy** [comment]
@toucham Do you have any thoughts? Seems to be a revolving issue with the menu!

**Comment by toucham** [comment]
> @toucham Do you have any thoughts? Seems to be a revolving issue with the menu!

I was working with Matt on this and forgot to look the impact of changing `mobile-cutoff` on other pages. I think the `mobile-cutoff` will have to be changed back to what it was originally and we have to fix the `display` of member cards instead. Either switch from `grid` to something else like `flex` or to something else that is more responsive to text and spacing.

**Comment by IanSaucy** [comment]
#69 fixes this

**Pull request closed without merging**
